# Generated by Django 4.2.7 on 2023-12-08 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.PositiveIntegerField()),
                ('credit', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('Face-to-Face', 'Face-to-Face'), ('Online', 'Online')], max_length=100)),
                ('description', models.TextField()),
                ('availability', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('credit', models.PositiveIntegerField()),
                ('description', models.TextField(default='No description provided.')),
                ('modules', models.ManyToManyField(to='students.module')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.course'),
        ),
    ]
