# Generated by Django 4.2.7 on 2023-12-08 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_module_course_profile_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='course',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
    ]
