# Generated by Django 4.2.7 on 2023-12-08 12:25

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.group')),
                ('description', models.TextField(blank=True)),
            ],
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.PositiveIntegerField()),
                ('credit', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('Face-to-Face', 'Face-to-Face'), ('Online', 'Online')], max_length=100)),
                ('description', models.TextField()),
                ('availability', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('credit', models.PositiveIntegerField()),
                ('description', models.TextField(default='No description provided.')),
                ('modules', models.ManyToManyField(to='Course.module')),
            ],
        ),
    ]
