# Generated by Django 4.2.7 on 2023-11-26 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ModuleRegistrationSystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.PositiveIntegerField()),
                ('credit', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('Face-to-Face', 'Face-to-Face'), ('Online', 'Online')], max_length=100)),
                ('description', models.TextField()),
                ('availability', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], max_length=100)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ModuleRegistrationSystem.course')),
            ],
        ),
        migrations.DeleteModel(
            name='Modules',
        ),
    ]
