# Generated by Django 4.2.7 on 2023-12-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ModuleRegistrationSystem', '0002_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='courses',
            field=models.ManyToManyField(to='auth.group'),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
