# Generated by Django 4.2.7 on 2023-12-15 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModuleRegistrationSystem', '0004_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
