# Generated by Django 4.2.7 on 2023-12-16 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ModuleRegistrationSystem', '0005_delete_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_registration', models.DateField(default=django.utils.timezone.now)),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='ModuleRegistrationSystem.module')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
